name: kopilka
description: Копилка — умный помощник для финансов
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.0.0

  # State management
  flutter_riverpod: ^2.5.1

  # Local storage
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

  # Charts
  fl_chart: ^0.68.0

  # Fonts
  google_fonts: ^6.2.1

  # Supabase
  supabase_flutter: ^2.5.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  path: ^1.9.0
  package_info_plus: ^8.0.0

  # Profile features
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9
  appmetrica_plugin: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0
  image: ^4.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#433DCB"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#F0F0F5"
  color_dark: "#1A1A2E"
  image: assets/icon/app_splash.png
  image_dark: assets/icon/app_splash.png
  android: true
  ios: false
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
